name: attt
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.1+4

environment:
  sdk: ">=2.1.0 <3.0.0"



dependencies:
  flutter:
    sdk: flutter
  firebase_auth: 
  cloud_firestore:
  flutter_twitter_login: 
    git: git://github.com/vudvhitech/flutter_twitter_login.git
  google_sign_in:
  splashscreen:
  flutter_signin_button:
  flutter_facebook_login: ^3.0.0
  shared_preferences:
  font_awesome_flutter: ^8.8.1
  url_launcher: ^5.4.2
  line_awesome_icons: ^1.0.4+2
  video_player: ^0.10.1
  chewie: ^0.9.7
  audioplayers: ^0.15.1
  after_init: ^0.1.2
  dio: any
  path_provider: ^1.6.7
  threading: ^0.0.10
  # flutter_ajanuw_android_pip: ^0.1.1
  video_box: ^0.12.0
  flutter_appavailability: ^0.0.21
  flutter_downloader: ^1.4.4
  intl:
  purchases_flutter: ^1.0.4
  provider: ^4.1.2
  connectivity: ^0.4.8+6
  overlay_container: ^0.0.4+1
  awesome_button: ^1.0.2
  flutter_picker:
    git: git://github.com/yangyxd/flutter_picker.git





  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.0"

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/images/athlete-logo.png"
  image_path_android: "assets/images/athlete-logo.png"
  adaptive_icon_background: "assets/images/athlete-logo.png"
  adaptive_icon_foreground: "assets/images/athlete-logo.png"


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/logo.png
    - assets/images/google-login.png
    - assets/images/athlete-logo.png
    - assets/images/athlete.png
    - assets/audio/bel.mp3
    - assets/audio/boxbel.mp3

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
